# Generated by Django 2.0.1 on 2018-03-01 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('B', (9, 10)), ('I', (16, 40)), ('A', (24, 99))], max_length=1)),
                ('finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('has_mine', models.BooleanField(default=False)),
                ('marked_as_mined', models.BooleanField(default=False)),
                ('x_cordenade', models.IntegerField()),
                ('y_cordenade', models.IntegerField()),
                ('value', models.IntegerField(blank=True, null=True)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Board')),
            ],
        ),
    ]
