# Generated by Django 2.0.1 on 2018-03-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='level',
            field=models.CharField(choices=[('B', 'BEGGINNER'), ('I', 'INTERMEDIATE'), ('A', 'ADVANCED')], max_length=1),
        ),
    ]
